// Track 1 "도름스 보안 검토" 카탈로그 (SSOT).
// 각 항목: id, group, severity(critical|high|medium|low|info), weight(점수),
//   track, plain(비개발자 설명), aiFix(교사 AI용 수정 프롬프트), gate(마크 게이트 대상 여부),
//   serverVerifiable(도름스 서버가 재검증 가능한 결정적 항목인지).
// {stack} 토큰은 report 렌더 시 실제 스택으로 치환.

export const SECURITY_ITEMS = [
  // ── 보안 응답 헤더 ──
  { id: 'sec.header.csp', group: '보안 헤더', title: 'Content-Security-Policy', severity: 'high', weight: 12, gate: true, serverVerifiable: true,
    plain: '외부에서 내 페이지에 악성 스크립트를 끼워넣는 공격(XSS)을 막는 기본 규칙이 없어요.',
    aiFix: "내 {stack} 앱의 모든 응답에 Content-Security-Policy 헤더를 넣어줘. Next.js면 middleware.ts에서 설정하고 최소한 default-src 'self'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self' 를 포함해줘. 인라인 스크립트가 필요하면 nonce 방식으로 허용해줘." },
  { id: 'sec.header.hsts', group: '보안 헤더', title: 'Strict-Transport-Security', severity: 'medium', weight: 6, gate: true, serverVerifiable: true,
    plain: '접속을 항상 암호화(https)로만 하도록 강제하는 설정이 빠졌어요.',
    aiFix: "{stack} 앱 응답에 Strict-Transport-Security: max-age=63072000; includeSubDomains 헤더를 추가해줘." },
  { id: 'sec.header.frame', group: '보안 헤더', title: '클릭재킹 방어(X-Frame-Options / frame-ancestors)', severity: 'medium', weight: 6, gate: true, serverVerifiable: true,
    plain: '내 화면을 남의 사이트가 몰래 안에 띄워 클릭을 가로채는 공격을 막는 설정이 없어요.',
    aiFix: "{stack} 앱에 X-Frame-Options: DENY 헤더(또는 CSP frame-ancestors 'none')를 추가해줘." },
  { id: 'sec.header.nosniff', group: '보안 헤더', title: 'X-Content-Type-Options: nosniff', severity: 'low', weight: 4, gate: true, serverVerifiable: true,
    plain: '브라우저가 파일 종류를 멋대로 추측해 생기는 공격을 막는 설정이 없어요.',
    aiFix: "{stack} 앱 응답에 X-Content-Type-Options: nosniff 헤더를 추가해줘." },
  { id: 'sec.header.referrer', group: '보안 헤더', title: 'Referrer-Policy', severity: 'low', weight: 3, gate: false, serverVerifiable: true,
    plain: '다른 사이트로 이동할 때 내 주소 정보가 과하게 새는 걸 막는 설정이 없어요.',
    aiFix: "{stack} 앱에 Referrer-Policy: strict-origin-when-cross-origin 헤더를 추가해줘." },
  { id: 'sec.header.permissions', group: '보안 헤더', title: 'Permissions-Policy', severity: 'low', weight: 3, gate: false, serverVerifiable: true,
    plain: '카메라·위치 같은 브라우저 권한 사용을 제한하는 설정이 없어요.',
    aiFix: "{stack} 앱에 필요한 기능만 허용하는 Permissions-Policy 헤더를 추가해줘(예: camera=(), geolocation=())." },
  { id: 'sec.fingerprint.powered-by', group: '보안 헤더', title: '서버/프레임워크 버전 노출', severity: 'info', weight: 0, gate: false, serverVerifiable: true,
    plain: 'x-powered-by 헤더로 사용 기술이 노출돼요. 공격 표적이 되기 쉬워요.',
    aiFix: "{stack} 앱에서 x-powered-by 헤더를 제거해줘(Next.js면 next.config 에 poweredByHeader:false)." },

  // ── 전송 보안 ──
  { id: 'sec.transport.https-redirect', group: '전송 보안', title: 'HTTPS 강제(HTTP→HTTPS 리다이렉트)', severity: 'high', weight: 8, gate: true, serverVerifiable: true,
    plain: 'http로 들어와도 암호화된 https로 자동 전환되지 않아, 중간에서 내용이 새거나 조작될 수 있어요.',
    aiFix: "{stack} 앱에서 http 요청을 https 로 강제 리다이렉트하도록 설정해줘." },
  { id: 'sec.transport.ssl-valid', group: '전송 보안', title: 'SSL 인증서 유효', severity: 'critical', weight: 10, gate: true, serverVerifiable: true,
    plain: '보안 인증서가 유효하지 않아요. 접속 자체가 안전하지 않다고 표시될 수 있어요.',
    aiFix: '호스팅(예: Vercel)에서 도메인의 SSL 인증서를 정상 발급받도록 도메인 설정을 확인해줘.' },
  { id: 'sec.transport.old-tls', group: '전송 보안', title: '구버전 TLS 미사용', severity: 'medium', weight: 4, gate: false, serverVerifiable: true,
    plain: '오래되고 취약한 암호화 방식(TLS 1.0/1.1)이 켜져 있어요.',
    aiFix: '호스팅에서 TLS 1.2 이상만 허용하도록 설정해줘.' },
  { id: 'sec.transport.cookie-flags', group: '전송 보안', title: '쿠키 보안 플래그(HttpOnly/Secure)', severity: 'medium', weight: 5, gate: true, serverVerifiable: true,
    plain: '로그인 쿠키에 보안 플래그가 없어 스크립트가 훔치거나 암호화 안 된 채 전송될 수 있어요.',
    aiFix: '세션/인증 쿠키에 HttpOnly 와 Secure, SameSite=Lax(또는 Strict) 플래그를 붙여줘.' },

  // ── 정보 유출 ──
  { id: 'info.secret-exposed', group: '정보 유출', title: '민감 파일 노출(.env/.git)', severity: 'critical', weight: 15, gate: true, serverVerifiable: true,
    plain: '.env 나 .git 같은 비밀 파일이 인터넷에 그대로 노출됐어요. 키·비밀번호가 새는 심각한 문제예요.',
    aiFix: "배포에서 .env 와 .git 이 공개되지 않도록 해줘. 노출된 키·토큰은 '즉시 재발급(rotate)'하고, 배포 산출물에서 해당 파일을 제외해줘." },
  { id: 'info.config-exposed', group: '정보 유출', title: '설정 파일 노출', severity: 'medium', weight: 4, gate: false, serverVerifiable: true,
    plain: 'next.config·vercel.json 같은 설정 파일이 직접 열려요. 내부 구조가 노출돼요.',
    aiFix: '배포에서 설정 파일이 정적으로 서빙되지 않도록 해줘.' },
  { id: 'info.source-map', group: '정보 유출', title: '소스맵 노출', severity: 'low', weight: 3, gate: false, serverVerifiable: true,
    plain: '빌드 소스맵이 노출돼 원본 코드가 복원될 수 있어요.',
    aiFix: '프로덕션 빌드에서 소스맵 생성을 끄거나 공개되지 않게 해줘(Next.js: productionBrowserSourceMaps:false).' },
  { id: 'info.stack-trace', group: '정보 유출', title: '에러 스택트레이스 노출', severity: 'medium', weight: 4, gate: true, serverVerifiable: true,
    plain: '오류 화면에 서버 내부 경로·코드 위치가 그대로 보여요. 공격 힌트가 돼요.',
    aiFix: '프로덕션에서 사용자에게 상세 에러/스택트레이스를 보여주지 말고 일반 오류 페이지로 처리해줘.' },
  { id: 'info.mixed-content', group: '정보 유출', title: 'Mixed Content', severity: 'low', weight: 3, gate: false, serverVerifiable: true,
    plain: 'https 페이지가 http 리소스를 불러와 암호화가 깨져요.',
    aiFix: '모든 리소스(이미지·스크립트)를 https 로 불러오도록 고쳐줘.' },

  // ── CORS ──
  { id: 'cors.policy', group: 'CORS', title: 'CORS 설정', severity: 'high', weight: 8, gate: true, serverVerifiable: true,
    plain: '아무 사이트나 내 API를 호출·인증정보까지 쓸 수 있게 열려 있으면, 남의 사이트가 내 사용자 데이터를 가져갈 수 있어요.',
    aiFix: 'CORS 를 신뢰하는 도메인만 허용하도록 좁혀줘. credentials 를 쓰는 API 는 Access-Control-Allow-Origin 을 * 로 두거나 요청 Origin 을 그대로 반사하지 말고 화이트리스트로 제한해줘.' },

  // ── 코드 내부(런타임 실측 + 정적) ──
  { id: 'code.rls.anon-read', group: '데이터 접근(RLS)', title: '익명 접근 차단(RLS)', severity: 'critical', weight: 15, gate: true, serverVerifiable: true,
    plain: '로그인하지 않은 사람이 데이터베이스의 개인정보를 그냥 읽을 수 있어요. 학생·회원 정보가 새는 가장 위험한 문제예요.',
    aiFix: 'Supabase 의 모든 테이블에 RLS(행 수준 보안)를 켜고, 개인정보가 든 테이블은 본인/권한 있는 사용자만 읽도록 정책을 만들어줘. 공개해도 되는 테이블만 익명 읽기를 허용해줘. 익명 anon 키로 실제 접속해서 개인정보 행이 안 나오는지 다시 확인해줘.' },
  { id: 'code.endpoint.unauth', group: '데이터 접근(RLS)', title: '미인증 API 접근', severity: 'high', weight: 8, gate: false, serverVerifiable: true,
    plain: '로그인 없이 호출해도 데이터를 돌려주는 API 후보가 있어요. 공개용이 아니면 인증을 걸어야 해요.',
    aiFix: '민감한 데이터를 반환하는 API 라우트에 인증/권한 확인을 추가해줘. 공개 API 라면 반환 데이터에 개인정보가 없는지 확인해줘.' },
  { id: 'code.hardcoded-secret', group: '코드 내부', title: '하드코딩 시크릿', severity: 'critical', weight: 12, gate: false, serverVerifiable: false,
    plain: '코드 안에 API 키·비밀번호가 직접 적혀 있어요. 코드가 새면 키도 같이 새요.',
    aiFix: '코드에 박힌 키·토큰을 환경변수(.env, 서버 전용)로 옮기고, 노출됐던 키는 즉시 재발급(rotate)해줘.' },
  { id: 'code.client-secret-leak', group: '코드 내부', title: '클라이언트 시크릿 노출', severity: 'critical', weight: 12, gate: false, serverVerifiable: false,
    plain: '브라우저로 내려가는 코드(NEXT_PUBLIC_ 등)에 서버 전용 비밀키가 들어 있어요. 사용자 누구나 볼 수 있어요.',
    aiFix: 'service_role 키 등 서버 전용 시크릿을 클라이언트(NEXT_PUBLIC_/VITE_) 변수에서 빼고 서버에서만 쓰도록 옮겨줘.' },
  { id: 'code.headers-config', group: '코드 내부', title: '헤더 설정 위치', severity: 'info', weight: 0, gate: false, serverVerifiable: false,
    plain: '보안 헤더가 설정 파일에 있는지 참고로 확인한 항목이에요(실제 판정은 라이브 관측을 우선해요).',
    aiFix: '' },
  { id: 'code.dangerous-pattern', group: '코드 내부', title: '위험 코드 패턴(검토 후보)', severity: 'info', weight: 0, gate: false, serverVerifiable: false,
    plain: 'eval·innerHTML 같은 주의가 필요한 코드가 있어요. 사용자 입력이 들어가면 위험할 수 있어 문맥 확인이 필요해요.',
    aiFix: '표시된 위치의 eval/innerHTML/exec 사용이 사용자 입력을 안전하게 처리하는지 확인하고, 위험하면 안전한 방식으로 바꿔줘.' },

  // ── 사칭·검색·성능(권고) ──
  { id: 'seo.title', group: '검색 노출', title: '페이지 제목', severity: 'info', weight: 1, gate: false, serverVerifiable: true, plain: '<title>이 없어요.', aiFix: '페이지에 <title>을 넣어줘.' },
  { id: 'seo.description', group: '검색 노출', title: '설명 메타', severity: 'info', weight: 1, gate: false, serverVerifiable: true, plain: 'meta description 이 없어요.', aiFix: 'meta name="description" 을 넣어줘.' },
  { id: 'seo.viewport', group: '검색 노출', title: '모바일 viewport', severity: 'info', weight: 1, gate: false, serverVerifiable: true, plain: 'viewport 메타가 없어 모바일 표시가 깨질 수 있어요.', aiFix: 'meta name="viewport" content="width=device-width, initial-scale=1" 을 넣어줘.' },
  { id: 'seo.og', group: '검색 노출', title: 'Open Graph', severity: 'info', weight: 1, gate: false, serverVerifiable: true, plain: '링크 공유 미리보기(OG) 태그가 없어요.', aiFix: 'og:title/og:description/og:image 메타를 넣어줘.' },
  { id: 'seo.canonical', group: '검색 노출', title: 'canonical', severity: 'info', weight: 0, gate: false, serverVerifiable: true, plain: 'canonical 링크가 없어요(중복 URL 정리에 도움).', aiFix: 'rel="canonical" 링크를 넣어줘.' },
  { id: 'perf.ttfb', group: '성능', title: '응답 속도', severity: 'info', weight: 0, gate: false, serverVerifiable: true, plain: '첫 응답이 느려요.', aiFix: '느린 원인(DB 왕복·큰 번들)을 찾아 줄여줘.' },
  { id: 'perf.page-size', group: '성능', title: '문서 크기', severity: 'info', weight: 0, gate: false, serverVerifiable: true, plain: 'HTML 문서가 커요.', aiFix: '불필요한 인라인 데이터를 줄여줘.' },
  { id: 'perf.compression', group: '성능', title: '압축', severity: 'info', weight: 0, gate: false, serverVerifiable: true, plain: '응답 압축(gzip/brotli)이 없어요.', aiFix: '호스팅에서 응답 압축을 켜줘.' },

  // ── 법적 표면(개인정보 앱이면 required) ──
  { id: 'legal.privacy-policy', group: '법적 표면', title: '개인정보처리방침', severity: 'high', weight: 6, gate: true, serverVerifiable: true,
    plain: '개인정보를 다루는 서비스는 개인정보처리방침을 반드시 공개해야 해요(개인정보 보호법 제30조).',
    aiFix: '개인정보처리방침 페이지(/privacy)를 만들어 링크를 노출해줘. dorms-check templates/privacy-policy.ko.md 를 골격으로 실제 수집 항목에 맞게 채워줘.' },
  { id: 'legal.terms', group: '법적 표면', title: '이용약관', severity: 'low', weight: 2, gate: false, serverVerifiable: true,
    plain: '이용약관 페이지가 있으면 좋아요.', aiFix: '이용약관 페이지(/terms)를 만들어줘.' },
  { id: 'legal.contact', group: '법적 표면', title: '연락처', severity: 'low', weight: 2, gate: false, serverVerifiable: true,
    plain: '문의할 연락처가 보이면 신뢰가 높아져요.', aiFix: '푸터 등에 문의 연락처(이메일)를 넣어줘.' },
];
